# Generated by Django 4.2.11 on 2024-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='negos', max_length=20),
            preserve_default=False,
        ),
    ]
