# Generated by Django 4.2.11 on 2024-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
